USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
ARTIST VARCHAR(100) NOT NULL,
NAME VARCHAR(100) NOT NULL,
-- YEAR DOESN'T WORK WITH UPDATE EXERCISE SO CHANGED TO INT:
RELEASE_DATE INT UNSIGNED NOT NULL,
SALES FLOAT,
GENRE VARCHAR(100) NOT NULL,
PRIMARY KEY (id)

);

