USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
ARTIST VARCHAR(100) NOT NULL,
NAME VARCHAR(100) NOT NULL,
RELEASE_DATE YEAR,
SALES FLOAT,
GENRE VARCHAR(100) NOT NULL,
PRIMARY KEY (id)

);

