USE codeup_test_db;

SELECT * FROM ALBUMS WHERE ARTIST = 'PINK FLOYD';
SELECT RELEASE_DATE FROM ALBUMS WHERE NAME =  'Sgt. Pepper' 's Lonely Hearts Club Band';
SELECT GENRE FROM ALBUMS WHERE NAME = 'NEVERMIND';
SELECT NAME FROM ALBUMS WHERE RELEASE_DATE BETWEEN 1990 AND 2000;
SELECT NAME FROM ALBUMS WHERE SALES <= 20;
SELECT NAME FROM ALBUMS WHERE GENRE = 'ROCK';
